[package]
name = "funicular"
version = "0.1.0"
authors = ["Vincent Serpoul <vincent@serpoul.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_yaml = "0.8"
semver = { version = "0.9.0", features = ["serde"] }
chrono = "0.4"
chrono-tz = { version = "0.5", features = ["serde"] }
serde_derive = "1.0"