[base]
arch = "aarch64"
hostname = "example"

[base.alpine]
mirror = "http://dl-cdn.alpinelinux.org/alpine"
version = "3.12.0"
timezone = "Asia/Singapore"
branch = "latest-stable"
keymap = "us us"

[base.networking]
dns_nameservers = ["8.8.8.8", "1.1.1.1"]

[base.ssh]
authorized_keys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMIVp6q5co/r5GwY0dH+NYQbfKicapeF3gXEU3dzaAvD me@home",
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCiChinH9volauTvLfGWv2xCIo0jrQAv0jCQjfDodZW+E1vLFUcgdULKemujxG2vLzLUHfSHF9mjnwnGbyHYZi1fEO70s3gGZNd9K2xwvkGo28svefCfNR3hi+jSB9Q9drvR7CgYdEY5D90Z/OfSWJ4a60/qpD7L3uXf5riqYddDUbHVlDg11SK27KHan33UAfskd5u2AccRbXKJX3I6oO78AwI4/fHs2N/RuoleYcsHX9FNaVX8NHxSEY7EXLTPmykRQj8/8ubjuflvm4qYTsW8cFtRETfxkgFMF0p375YEVQles/6JwRsljnVaobiyeNG1u/5p4zaEguuqN7oVpsP me@home"
]

[base.users]
root_password = "rootpass"
remote_user = "funi"
remote_user_password = "funipass"

[[provisioners]]
name = "wlan"
script_path = "./scripts/provisioners/wlan.sh"
[provisioners.environment_vars]
ssid = "wifi"
password = "passwifi"

[[provisioners]]
name = "two_factor_auth"
script_path = "./scripts/provisioners/two_factor_auth.sh"
lbu_additions = ["/var/test", "/usr/testa"]
[provisioners.environment_vars]
secret = "ADCGGDI"

[[provisioners]]
name = "udev"
script_path = "./additional_provisioners/udev.sh"
lbu_additions = ["/testttt.txt"]
[provisioners.environment_vars]
test = "TEST"